Repository Social-Ctrl-Dev/ctrl-dev-back, pull requests merged in 2023-02, with the labels that each got.

#9 ft-update_model+create_password+update_password+get_user
  package-lock.json
  package.json
  prisma/migrations/20230131180731_update_user_model/migration.sql
  prisma/schema.prisma
  src/components/like/index.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/interface/user.ts
Labels: feature

#10 Fix/cors
  .env.example
  src/app.ts
  src/components/post/index.ts
Labels: bug

#11 Development
  .env.example
  package-lock.json
  package.json
  prisma/migrations/20230130234245_table_comment/migration.sql
  prisma/migrations/20230131070042_fixcommenttable/migration.sql
  prisma/migrations/20230131091019_add_likes_table/migration.sql
  prisma/migrations/20230131110230_add_like_model/migration.sql
  prisma/migrations/20230131180731_update_user_model/migration.sql
  prisma/schema.prisma
  src/app.ts
  src/components/comment/controller.ts
  src/components/comment/index.ts
  src/components/index.ts
  src/components/like/controller.ts
  src/components/like/index.ts
  src/components/post/controller.ts
  src/components/post/index.ts
  src/components/tag/controller.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/interface/like.ts
  src/interface/user.ts
Labels: enhancement

#12 Release 1.1.0
  .env.example
  .gitignore
  env.txt
  package-lock.json
  package.json
  prisma/migrations/20230130060836_add_user_and_rol_table/migration.sql
  prisma/migrations/20230130155615_tablepoststags/migration.sql
  prisma/migrations/20230130184830_fixtables/migration.sql
  prisma/migrations/20230130234245_table_comment/migration.sql
  prisma/migrations/20230131070042_fixcommenttable/migration.sql
  prisma/migrations/20230131091019_add_likes_table/migration.sql
  prisma/migrations/20230131110230_add_like_model/migration.sql
  prisma/migrations/20230131180731_update_user_model/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.ts
  src/components/comment/controller.ts
  src/components/comment/index.ts
  src/components/index.ts
  src/components/like/controller.ts
  src/components/like/index.ts
  src/components/post/controller.ts
  src/components/post/index.ts
  src/components/tag/controller.ts
  src/components/tag/index.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/interface/like.ts
  src/interface/user.ts
  src/middleware/supabase-middleware.js
  src/responses/index.ts
  src/services/supabase.ts
Labels: enhancement

#13 phone verification with Twilio and AwsLambda
  .env.example
  src/components/user/controller.ts
  src/components/user/index.ts
Labels: feature

#14 Fix/databases
  README.md
  prisma/migrations/20230201215350_fix_on_delete/migration.sql
  prisma/schema.prisma
  src/components/comment/controller.ts
  src/components/post/controller.ts
  src/components/tag/controller.ts
  src/components/tag/index.ts
Labels: enhancement

#15 Fix/12 tsconfig json middleware to dist
  src/components/user/controller.ts
  tsconfig.json
Labels: bug

#16 fix_fetch-to-axios
  .gitignore
  package-lock.json
  package.json
  src/components/user/controller.ts
Labels: bug

#17 Discord+Github-WebHook_PullRequest
  .env.example
  package-lock.json
  package.json
  src/app.ts
  src/components/index.ts
  src/components/webhook/controller.ts
  src/components/webhook/index.ts
Labels: feature

#19 Update PUT Post & PUT delete tags from one post
  src/components/post/controller.ts
  src/components/post/index.ts
Labels: bug

#20 Test/api post tag comment
  __test/comment.test.ts
  __test/demo.test.ts
  __test/post.test.ts
  __test/tag.test.ts
  package-lock.json
  package.json
  src/app.ts
  src/components/demo/controller.ts
  src/components/demo/index.ts
  src/components/index.ts
  src/components/post/controller.ts
  src/components/tag/controller.ts
  src/components/test/controller.ts
  src/components/test/index.ts
  vite.config.ts
Labels: enhancement

#21 fix add user update
  src/components/user/controller.ts
  src/components/user/index.ts
Labels: bug

#22 fix/components2
  src/components/index.ts
  src/components/like/controller.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/interface/like.ts
  src/middleware/supabase-middleware.js
  src/services/supabase.ts
Labels: enhancement

#23 Development
  .env.example
  .gitignore
  README.md
  __test/comment.test.ts
  __test/demo.test.ts
  __test/post.test.ts
  __test/tag.test.ts
  package-lock.json
  package.json
  prisma/migrations/20230201215350_fix_on_delete/migration.sql
  prisma/schema.prisma
  src/app.ts
  src/components/comment/controller.ts
  src/components/demo/controller.ts
  src/components/demo/index.ts
  src/components/index.ts
  src/components/like/controller.ts
  src/components/post/controller.ts
  src/components/post/index.ts
  src/components/tag/controller.ts
  src/components/tag/index.ts
  src/components/test/controller.ts
  src/components/test/index.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/components/webhook/controller.ts
  src/components/webhook/index.ts
  src/interface/like.ts
  src/middleware/supabase-middleware.js
  src/services/supabase.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#24 Release 1.5
  .env.example
  .gitignore
  README.md
  __test/comment.test.ts
  __test/demo.test.ts
  __test/post.test.ts
  __test/tag.test.ts
  package-lock.json
  package.json
  prisma/migrations/20230201215350_fix_on_delete/migration.sql
  prisma/schema.prisma
  src/app.ts
  src/components/comment/controller.ts
  src/components/demo/controller.ts
  src/components/demo/index.ts
  src/components/index.ts
  src/components/like/controller.ts
  src/components/post/controller.ts
  src/components/post/index.ts
  src/components/tag/controller.ts
  src/components/tag/index.ts
  src/components/test/controller.ts
  src/components/test/index.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/components/webhook/controller.ts
  src/components/webhook/index.ts
  src/interface/like.ts
  src/middleware/supabase-middleware.js
  src/services/supabase.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement
